blank_issues_enabled: true
contact_links:
  - name: C-PAT Documentation
    url: http://c-pat.readthedocs.io/
    about: Please review our documentation for help with C-PAT.
  - name: Contact Us
    url: https://dod.teams.microsoft.us/l/team/19%3Adod%3AODkXfTLAxungD6xHi3ae-XHC1AW9hU_h_x77eJQoaOA1%40thread.tacv2/conversations?groupId=a6a733ca-a5bf-45ee-9830-6f5c99c5b580&tenantId=e3333e00-c877-4b87-b6ad-45e942de1750
    about: If you have a question or need assistance that can not be answered via GitHub, please join our Teams channel.
