name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=NSWC-Crane_C-PAT
            -Dsonar.organization=nswc-crane
            -Dsonar.sources=client,api
            -Dsonar.inclusions=**/*.ts,**/*.js,**/*.html,**/*.css
            -Dsonar.exclusions=**/node_modules/**
            -Dsonar.scm.provider=git
            -Dsonar.verbose=true
          projectBaseDir: .
